title: THETA
remote_theme: jeffreytse/jekyll-theme-yat
author: Koyomiya5438
copyright: "(cleft) 2022-{currentYear} {author}"
yat:
  date_format: "%Y年%m月%d日"
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-spaceship
