title: THETA
remote_theme: jeffreytse/jekyll-theme-yat
author: Koyomiya5438
copyright: "(cleft) 2022-{currentYear} {author}"
yat:
  date_format: "%Y/%m/%d"
lang: "ja"
brand_color: "#45bad1"
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: /:year-:month/:title.html
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
